name: time-series-forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel=6.29.4
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - xgboost=2.0.3
  - statsmodels=0.14.1
  - scipy=1.13.0
  - shap=0.45.0
  - plotly=5.21.0
  - nbformat=5.10.3
  - optuna=3.6.1
  - lightgbm=4.3.0
  - jupyterlab  # Optional but helpful
  - pip:
      - prophet==1.1.5
